### ISSUE TITLE
Freezer failing in fix/japanese version

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/galyleo-dashboard#161]
[build-err.log](https://github.com/engageLively/galyleo-dashboard/files/10787803/build-err.log)

Trace attached.  the original command was
`$ npm run build`

**Comment by rickmcgeer** [comment]
This appears to be an issue in Ubuntu-on-windows.  When I ran it in the Docker container it worked fine.

**Comment by merryman** [comment]
I dont know but node 19 is not yet supported. How were you able to run install? That usually prohibits execution of anything above 18...

**Comment by merryman** [comment]
> This appears to be an issue in Ubuntu-on-windows. When I ran it in the Docker container it worked fine.

Because it uses the proper node.js version
