### ISSUE TITLE
Sliders are still too big and filled with whitespace

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/galyleo-dashboard#170]
Even after merging and doing a pull, I'm still seeing this:
![Screenshot 2023-06-12 183225](https://github.com/engageLively/galyleo-dashboard/assets/656259/597138c3-1672-45f1-ad19-be34b499fb61)

I tried to fix this myself; it appears that the problem is in 
```
$world.execCommand("open browser", {moduleName: "studio/inputs/slider.cp.js", packageName: "galyleo-dashboard", codeEntity: "IncrementButton"});
```
and in 
```
$world.execCommand("open browser", {moduleName: "studio/inputs/slider.cp.js", packageName: "galyleo-dashboard", codeEntity: "SliderInputLabel"});
```
No matter how I shrink the text and padding in these components, when I instantiate in a `SliderWIthValue` there's still a ton of whitespace.  It appears to be in the layout, and I still don't understand this as well as I should.  Can you take a look?

**Comment by merryman** [comment]
I am pretty sure this is because of caching in either server or browser. Please make sure you restart the server and cleaned your browser cache.
