### ISSUE TITLE
Clicking on the Shape Menu on the Top Bar gives a Type Error bubble

### ISSUE THREAD

**Issue by rickmcgeer** [engageLively/galyleo-dashboard#191]
The error is "TypeError: Cannot read properties of undefined (reading 'primaryTarget')
As I trace the code, it's in `setEditMode` in `$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "lively.ide", codeEntity: "TopBarModel"});` and it _appears_ that `this` is undefined.  I don't see how this can be.  Galyleo's `TopBar` (`$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "GalyleoTopBar"});`) is a thin extension of the lively.ide `TopBar`.  All I can think is that the signalling protocol has changed and the code in "GalyleoTopBar" needs to reflect this change.

**Comment by merryman** [comment]
I will take a look.

**Comment by merryman** [comment]
This was an issue with lively core. If you update to the latest version now, this bug should be gone.

**Comment by rickmcgeer** [comment]
Now I am seeing this when I attempt to open  `GalyleoDashboardStudio`.  I am seeing this error message in the red box in Lively.  Executing:
```
part(GalyleoDashboardStudio).openInWorld()
```
gives this:
```
TypeError: Cannot read properties of undefined (reading 'view')

    at ViewModel.ViewModel_getProperty_ (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:94647:35)
    at ViewModel.defaultGetter (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:95064:29)
    at ViewModel.getter [as view] (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:121285:36)
    at ViewModel.ViewModel_doWithScope_ (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:94677:25)
    at ViewModel.get [as ui] (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:95153:24)
    at ViewModel.get [as bindings] (http://127.0.0.1:9011/lively.ide/studio/top-bar.cp.js:1379:62)
    at GalyleoTopBarModel.get [as bindings] (http://127.0.0.1:9011/local_projects/engageLively--galyleo-dashboard/studio/top-bar.cp.js:255:136)
    at GalyleoTopBarModel.ViewModel_reifyBindings_ (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:94750:61)
    at GalyleoTopBarModel.ViewModel_attach_ (http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:95028:18)
    at http://127.0.0.1:9011/dashboard/__rootModule___commonjs-entry-1b56242d.js:87730:34
```

Unfortunately, this is _not_ the error message in the console.  There, I am seeing:
"cannot compute bounds for line 0/109"
with a completely different stack

```
$world.execCommand("open browser", {moduleName: "studio/ui.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "GalyleoDashboardStudio"});
```

**Comment by rickmcgeer** [comment]
A little experimentation showed that if I commented out the `bindings` property in `GalyleoTopBarModel` it loaded, but of course the `Help` and `Publish` buttons were inactive.  
```
bindings: {
        /* get () {
          return super.prototype.bindings.concat([
            { target: 'help button', signal: 'onMouseDown', handler: 'reportBug' },
            { target: 'upload button', signal: 'onMouseDown', handler: 'publishDashboard' }
          ]);
        } */
      }
```
works
```
$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "viewDidLoad"});
```

**Comment by rickmcgeer** [comment]
It's the `super.prototype.bindings` that is failing.  I tried
```
bindings: {
        get () {
          return super.prototype.bindings;
        }
       }
    };
```
And this showed the same error

**Comment by rickmcgeer** [comment]
OK, I fixed this with a workaround -- I just copied the bindings from ```$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "lively.ide", codeEntity: "bindings"});``` to `GalyleoTopBarModel` and it worked fine.  So I will just leave that in.  This feels like a hack, though, and I suspect that there's a null pointer -- but I don't know why `super.prototype.bindings`  and `super.bindings` were null...

**Comment by merryman** [comment]
I am sorry, the fix we pushed could have never worked. I will merge one into main today that will *definitely* fix this issue. Sorry for the inconvenience.

**Comment by merryman** [comment]
Its merged now, please try again without your workaround.

**Comment by rickmcgeer** [comment]
This now works with acaf0fc025a77f874d9c036b7827cdcaf624afee.  Thanks, @merryman !
