### ISSUE TITLE
Spelling mistake in Japanese display

### ISSUE THREAD

**Issue by Shima-Nao** [engageLively/galyleo-dashboard#194]
![image](https://github.com/engageLively/galyleo-dashboard/assets/91653807/6ac08e36-8d64-40e0-b5fa-1349ad7e14e7)
![image](https://github.com/engageLively/galyleo-dashboard/assets/91653807/cf5713b9-4512-478d-9aff-125e25913135)

[公開してったダッシュボード] is mistaken,

[公開されたダッシュボード] is correct.

**Comment by Shima-Nao** [comment]
@rickmcgeer @merryman 
Please fix it asap. Thank you.

**Comment by rickmcgeer** [comment]
@Shima-Nao thanks to @merryman  there is a fix.  I am testing on my local system and should deploy tomorrow

**Comment by rickmcgeer** [comment]
@Shima-Nao this should now be fixed.  Please verify

**Comment by Shima-Nao** [comment]
![image](https://github.com/engageLively/galyleo-dashboard/assets/91653807/0dfdb650-d07d-4eb9-85e1-32e2c19bd236)

@rickmcgeer @merryman 
I'm confirm using a Japanese environment (7 May JST), but the messages are still in English.
Deployed not yet?

**Comment by merryman** [comment]
@rickmcgeer It seems like https://github.com/engageLively/galyleo-dashboard/commit/4b53c781e435305cd2781a62ef590df4a09c8343 broke the dispatch to the dashboard object that originally was handling the publish prompt. Is there a reason for why you decoupled that? Thats why the changes I did to the component to propagate through.

**Comment by rickmcgeer** [comment]
It was my error, fixing today.  This has led to some issues which I've gone into in some detail with the Lively repo.
@Shima-Nao I expect to have this sorted out by tomorrow.  It's a minor change

**Comment by rickmcgeer** [comment]
@merryman I made the changes to address https://github.com/engageLively/galyleo-dashboard/issues/188.  I had traced the issue to the non-propagation of the signals `initiate bug report` and `initiate publication`
See:
```
$world.execCommand("open browser", {moduleName: "studio/top-bar.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: [{"name":"GalyleoTopBarModel","type":"class-decl"},{"name":"reportBug","type":"class-instance-method"}]});
```
The signal handlers are specified in 
```
$world.execCommand("open browser", {moduleName: "studio/ui.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: "_topBarNetworkIndicator"});
```
In particular:
```
{ target: 'top bar', signal: 'initiate bug report', handler: 'reportBug' },
{ target: 'top bar', signal: 'initiate publication', handler: 'publishDashboard' }
```
Following the advice of @linusha , I changed `model` to `target` in these bindings.  
However, it is clear that
```
$world.execCommand("open browser", {moduleName: "studio/ui.cp.js", packageName: "engageLively--galyleo-dashboard", codeEntity: [{"name":"Galyleo","type":"class-decl"},{"name":"publishDashboard","type":"class-instance-method"}]});
```
is not getting invoked.
I've now checked in this code, and will file a ticket referring to it in the Lively Next repo, since this appears to be an issue with bindings.
If push comes to shove I'll simply called the `Galyleo` methods directly from the `TopBarModel` code, so one way or another we will get this resolved this week.

**Comment by rickmcgeer** [comment]
Fixed on the development system, will build and deploy

**Comment by Shima-Nao** [comment]
![image](https://github.com/engageLively/galyleo-dashboard/assets/91653807/c2ddabd7-9812-4f47-8a97-e7b89d1c6f4a)

@rickmcgeer 
I've tried several times, but it always times out and fails to start. Could you please review the config?

**Comment by rickmcgeer** [comment]
@Shima-Nao according to the logs the cluster looks fine, but I am replicating this.  I will need to look into it with Google tomorrow morning Pacific time,

**Comment by rickmcgeer** [comment]
@Shima-Nao a quick update.  This appears to be a Google issue.  We've brought up a clean copy of the Hub and can transfer the kct-free accounts to it, but the storage is tied to the old Hub.  We're working to recover that.   I've asked that we bring this up tomorrow.

**Comment by Shima-Nao** [comment]
@rickmcgeer I got it. I understand that you are currently troubleshooting. thank you so much.

**Comment by Shima-Nao** [comment]
@rickmcgeer @merryman 

The wording revisions have been completed, so this ticket can be closed.
*Any other issues will be addressed in a separate ticket.
