### ISSUE TITLE
The display appears incorrect when creating a view.

### ISSUE THREAD

**Issue by Shima-Nao** [engageLively/galyleo-dashboard#198]
@rickmcgeer @merryman @mhemmings-engage 
*Please refer to the video.

After creation, the display of the "Column Selector" is incorrect.
Example: Even after checking out, it reappears when touching other parts, etc.
"Update view" and "CLOSE" do not seem to function.

https://github.com/engageLively/galyleo-dashboard/assets/91653807/b0fe6bf6-0a3b-48bb-9746-6c2628ab238a

**Comment by rickmcgeer** [comment]
We're traced this error and it's due to a change in the underlying UI.  We're working to make this consistent with the new UI and we expect a fix this week
